apiVersion: v1
kind: Service
metadata:
  name: {{ include "rhaiis.fullname" . }}
  labels:
    {{- include "rhaiis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "rhaiis.selectorLabels" . | nindent 4 }}