apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-results
  labels:
    {{- include "whisper-benchmark.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.resultsSize }}