apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "guidellm.fullname" . }}-results
  labels:
    {{- include "guidellm.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.resultsSize | default "1Gi" }}