apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-results
  labels:
    app: whisper-benchmark
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi